name: Coverage
on:
  push:
    branches:
      - "*"
    paths:
      - "**coverage.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: x64
          distribution: full
          variant: "CS"
          version: "stable"
          packages: "cover, cover-badge"
      - run: raco pkg install --no-docs --auto --skip-installed
      - run: raco pkg install --auto --skip-installed
      - run: |
          xvfb-run -a raco test .
          xvfb-run -a raco cover .
          raco cover-badge
